recommendation_root: recommendation_data


data_ingestion:
  root_dir: recommendation_data/data_ingestion
  source_URL: https://github.com/gssrenathkumar/Dataset/raw/main/Movie_Recommendation_Dataset.zip
  local_data_file: recommendation_data/data_ingestion/data.zip
  unzip_dir: recommendation_data/data_ingestion

data_validation:
  root_dir: recommendation_data/data_validation
  STATUS_FILE: recommendation_data/data_validation/status.txt
  ALL_REQUIRED_FILES: ["dataset"]